/* Histórico de versões do portal, exibido ao clicar no número da versão no
   cabeçalho (ver layout.js).

   PARA REGISTRAR UMA VERSÃO NOVA: acrescente um objeto no TOPO da lista —
   ela é exibida na ordem em que está aqui, da mais recente para a mais
   antiga. `itens` é opcional e serve para detalhar o que muda para quem usa
   a ferramenta; sem ele, só o título aparece.

     { v:"3.20", data:"2026-08-25", titulo:"O que mudou, em uma linha",
       itens:["Detalhe 1.", "Detalhe 2."] }

   A versão do topo deve bater com VERSAO_APP, em ferramentas.js — o
   cabeçalho marca como "atual" a entrada cujo `v` for igual a ela.

   As entradas antigas foram geradas a partir das mensagens de commit; daqui
   em diante são escritas à mão, junto com o commit da versão. */

const CHANGELOG = [
  { v:"3.20.2", data:"2026-09-17", titulo:"Ponto 26: leitura de candidatos com múltiplas reservas no edital",
    itens:["Linhas com mais de um código de reserva separado por vírgula agora são reconhecidas, inclusive quando há espaços ao redor da vírgula.",
            "Todos os códigos de reserva são preservados na leitura, inclusive para nomes quebrados em mais de uma linha."] },
  { v:"3.20.1", data:"2026-09-17", titulo:"Ponto 26: correção na leitura do PDF de classificação final",
    itens:["Editais com a palavra Curitiba em uma linha do cabeçalho agora têm a tabela de classificação reconhecida corretamente.",
            "O fim da tabela pelo bloco de assinatura passa a ser considerado somente após o primeiro registro de candidato."] },
  { v:"3.20", data:"2026-08-21", titulo:"Histórico de versões: clique no número da versão para ver o que mudou",
    itens:["O número da versão, no canto do cabeçalho, passou a abrir este histórico.",
            "As versões anteriores foram recuperadas a partir do histórico do projeto; as novas passam a ser descritas junto com cada publicação."] },
  { v:"3.19", data:"2026-08-21", titulo:"Convocação da Residência: pré-seleção pelo relatório de aprovados da Fábrica",
    itens:["Convocação da Residência: etapa opcional no Passo 1 para enviar o Relatório de aprovados (.xlsx) da Fábrica de Provas.",
            "Os aprovados já vêm marcados e com a nota preenchida; os reprovados entram desmarcados.",
            "O cruzamento é pelo nome — aprovados sem correspondência na lista viram aviso, para marcação à mão."] },
  { v:"3.18", data:"2026-08-20", titulo:"Resultado Final: trava ao finalizar, exclusão no admin e SQL re-executável",
    itens:["Tabela de Resultado Final: finalizar agora bloqueia a edição e libera os documentos; há botão para voltar a editar.",
            "Área administrativa ganhou exclusão de registros gravados.",
            "Cabeçalho do documento: título passou a ser TABELA DE CLASSIFICAÇÃO FINAL, com a unidade abaixo dele."] },
  { v:"3.17", data:"2026-08-19", titulo:"Nova seção UE: Criação da tabela de resultado final; menu e cabeçalho",
    itens:["Nova seção Unidades Externas (UE), com a Criação da tabela de resultado final.",
            "PDF baixado direto, sem passar pela caixa de impressão.",
            "Menu enxugado: Processo Seletivo virou Estágio; a sigla da unidade no cabeçalho mostra o nome por extenso."] },
  { v:"3.16", data:"2026-08-11", titulo:"Blocos \"Como funciona\" recolhidos por padrão em toda ferramenta; ajustes de texto no Ponto 26",
    itens:["Blocos “Como funciona” passam a abrir recolhidos em todas as ferramentas."] },
  { v:"3.15.1", data:"2026-08-11", titulo:"Consulta de Vagas: nome da unidade quebra linha; bloco de ajuda recolhido" },
  { v:"3.15", data:"2026-08-11", titulo:"Nova seção Divisão de Gestão: Consulta de Vagas Disponíveis por Unidade",
    itens:["Nova seção Divisão de Gestão, com a Consulta de Vagas Disponíveis por Unidade.",
            "Busca por sigla, comarca, tipo ou nome, e comparação de várias unidades lado a lado."] },
  { v:"3.14", data:"2026-08-11", titulo:"Edital de Abertura: preenche Unidade solicitante pela sigla SEI",
    itens:["Gerador do Edital de Abertura: a sigla SEI da unidade sugere o nome por extenso, sempre marcado para conferência."] },
  { v:"3.13", data:"2026-08-07", titulo:"Fluxo: sempre carrega da nuvem; cabeçalho mostra a versão do portal",
    itens:["Editor do Fluxo passa a carregar sempre da nuvem, evitando mostrar dados antigos.",
            "O número da versão do portal passa a aparecer no cabeçalho."] },
  { v:"3.12.1", data:"2026-08-07", titulo:"Classificação Final e Convocação: coluna IDADE mostra anos e dias" },
  { v:"3.12", data:"2026-08-07", titulo:"Classificação Final e Convocação: idade como desempate",
    itens:["Classificação Final e Convocação: idade passa a desempatar candidatos com a mesma nota (mais velho primeiro)."] },
  { v:"3.11.1", data:"2026-08-05", titulo:"Convocação para Entrevista: alinhamento, horário, telefone e placeholders" },
  { v:"3.11", data:"2026-08-05", titulo:"Convocação para Entrevista: reescrita completa no padrão da Classificação Final" },
  { v:"3.10.7", data:"2026-08-04", titulo:"Classificação Final: harmoniza botões do Passo 1" },
  { v:"3.10.6", data:"2026-08-04", titulo:"Classificação Final: Bloco 3 só o número, negrito real no Bloco 4" },
  { v:"3.10.5", data:"2026-08-04", titulo:"Classificação Final: remove salvamento automático, ajusta blocos impressos" },
  { v:"3.10.4", data:"2026-08-04", titulo:"Classificação Final: confirmação de salvamento, seleção e maiúsculas" },
  { v:"3.10.3", data:"2026-08-04", titulo:"Classificação Final: sair do bloco de edição salva sozinho" },
  { v:"3.10.2", data:"2026-08-04", titulo:"Classificação Final: título da cota antes do cabeçalho, centralizado" },
  { v:"3.10.1", data:"2026-08-04", titulo:"Hércules da Residência: corrige reconhecimento de PPP" },
  { v:"3.10", data:"2026-08-04", titulo:"Residência: Gerador do Edital de Classificação Final" },
  { v:"3.9.2", data:"2026-08-03", titulo:"Eyebrow \"Ponto X\" na SPS e campo Observações no ensalamento" },
  { v:"3.9.1", data:"2026-07-31", titulo:"Menu: seção com uma ferramenta só vira link direto" },
  { v:"3.9", data:"2026-07-31", titulo:"Home: cartão \"Próxima ferramenta\" só na seção de Processo Seletivo" },
  { v:"3.8.3", data:"2026-07-31", titulo:"Fluxo: campos que se dimensionam sozinhos, no lugar de textarea" },
  { v:"3.8.2", data:"2026-07-31", titulo:"Fluxo: grade sem caixas, conteúdo centrado e cor colada ao texto" },
  { v:"3.8.1", data:"2026-07-31", titulo:"Fluxo: coluna Fase sempre em branco e sem o seletor de fase padrão" },
  { v:"3.8", data:"2026-07-31", titulo:"Nova seção: Fluxo de Processo Seletivo" },
  { v:"3.7", data:"2026-07-31", titulo:"Hércules da Residência: reordenação manual da tabela e exemplos fictícios" },
  { v:"3.6", data:"2026-07-31", titulo:"Gerador CSV Residência" },
  { v:"3.5", data:"2026-07-30", titulo:"Arka dos noia" },
  { v:"3.4.2", data:"2026-07-29", titulo:"Modalidade sobe para o passo 2, ao lado das colunas extras" },
  { v:"3.4.1", data:"2026-07-29", titulo:"Ponto 18 avisa quando falta o link da sala e esconde a coluna Link no presencial" },
  { v:"3.4.0", data:"2026-07-29", titulo:"Ponto 18 com modalidade funcional: campos por modalidade e LINK da sala" },
  { v:"3.3.0", data:"2026-07-29", titulo:"Ponto 20 com SEI como etapa 3, quantidade opcional e blocos na ordem do Athos" },
  { v:"3.2.1", data:"2026-07-29", titulo:"Quadro do resultado da lista de e-mails só aparece depois de gerar" },
  { v:"3.2.0", data:"2026-07-29", titulo:"Seletor de horário próprio, ajustes de usabilidade no Ponto 18 e blocos do Athos no Ponto 20" },
  { v:"3.1.0", data:"2026-07-28", titulo:"Padronização de endereços, PDF do ensalamento e datas/horários do Ponto 18" },
  { v:"3.0", data:"2026-07-28", titulo:"Adição do gerador do edital de ensalamento" },
  { v:"2.2.1", data:"2026-07-27", titulo:"Espaço entre parágrafos compacto só no Preâmbulo e na Numeração" },
  { v:"2.2.0", data:"2026-07-27", titulo:"Rascunho .json no edital de abertura e blocos do Athos sem espaço entre parágrafos" },
  { v:"2.1.2", data:"2026-07-27", titulo:"Entrelinha simples e negrito nos blocos do Athos do edital de abertura" },
  { v:"2.1.1", data:"2026-07-27", titulo:"Bloco de Data do Athos só com a data por extenso" },
  { v:"2.1.0", data:"2026-07-27", titulo:"Blocos do Athos remodelados, borda 1pt na tabela e assunto do e-mail" },
  { v:"2.0.3", data:"2026-07-27", titulo:"Negrito só na etiqueta e nome do candidato à esquerda" },
  { v:"2.0.2", data:"2026-07-27", titulo:"Fonte única no documento gerado e nos blocos do Athos" },
  { v:"2.0.1", data:"2026-07-27", titulo:"Correção de alinhamento no Chrome e entrelinhas simples nos blocos do Athos" },
  { v:"2.0", data:"2026-07-27", titulo:"Reorganização do portal em seções" },
  { v:"0.11.1", data:"2026-07-23", titulo:"Correção na leitura de PDF com nomes quebrados em duas linhas - Ponto 26" },
  { v:"0.10.3", data:"2026-07-22", titulo:"Adicionado Bloco de Título do Edital no Gerador de Convocação" },
  { v:"0.10.2", data:"2026-07-22", titulo:"Ajustes finos no Gerador de Convocação - terminologia Nota, ponto final e largura das colunas" },
  { v:"0.10.1", data:"2026-07-22", titulo:"Ajustes no Gerador de Convocação - blocos separados, coluna Nota e importação Ordem/Nome/Nota" },
  { v:"0.10", data:"2026-07-22", titulo:"Reforma do Gerador de Convocação para Entrevista - Residência" },
  { v:"0.9.1", data:"2026-07-22", titulo:"Adicionado campo \"Data para colar no Athos\" - Ponto 20" },
  { v:"0.9", data:"2026-07-21", titulo:"Implementação Residência" },
  { v:"0.8", data:"2026-07-21", titulo:"Adicionada seção Residência" },
  { v:"0.7.2", data:"2026-07-21", titulo:"Correção lógica - supressão coluna RESERVA" },
  { v:"0.7.1", data:"2026-07-20", titulo:"Ajuste na legenda - Ponto 26" },
  { v:"0.7", data:"2026-07-20", titulo:"Ponto 26 BETA - Planilha de inscritos fábrica de provas" },
  { v:"0.6.2", data:"2026-07-20", titulo:"Alteração no campo de ANEXO I CONTEÚDO PROGRAMÁTICO" },
  { v:"0.6.1", data:"2026-07-20", titulo:"Correções gerais" },
  { v:"0.6", data:"2026-07-20", titulo:".extra" },
  { v:"0.5.9", data:"2026-07-18", titulo:"Tag Obrigatório e avisos no gerador" },
  { v:"0.5.8", data:"2026-07-18", titulo:"Ajustes de header e header fixo" },
  { v:"0.5.6", data:"2026-07-18", titulo:"update botões" },
  { v:"0.5.4", data:"2026-07-17", titulo:"Melhorias visuais" },
  { v:"0.5.2", data:"2026-07-17", titulo:"correções no gerador de PDF" },
  { v:"0.5.1", data:"2026-07-17", titulo:"ajuste na estrutura de pastas" },
  { v:"0.5", data:"2026-07-17", titulo:"Primeira versão do gerador de edital" }
];
